In [6]:
## Example given from: https://towardsdatascience.com/how-to-build-your-own-neural-network-from-scratch-in-python-68998a08e4f6

import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)



In [7]:

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

        #adding just to print
        self.d_weights2 = self.weights1
        self.d_weights2 = self.weights2

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # adding just to print
        self.d_weights2 = d_weights1
        self.d_weights1 = d_weights2
        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

In [8]:
# Input
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

# Output
y = np.array([[0],[1],[1],[0]])

# NN object
nn = NeuralNetwork(X,y)


In [9]:
for i in range(2):
    nn.feedforward()
    nn.backprop()
    print(f'------ Iteration {i} ---------')
    print('Layer 1')
    print(nn.layer1)
    print('Input')
    print(nn.input)
    print('Weights 1')
    print(nn.weights1)
    print('Weights 2')
    print(nn.weights2)
    print('D Weights 1')
    print(nn.d_weights1)
    print('D Weights 2')
    print(nn.d_weights2)
    print('Output')
    print(nn.output)

In [10]:
for i in range(300):
    nn.feedforward()
    nn.backprop()
    if i >= 297:
        print(f'------ Iteration {i} ---------')
        print('Layer 1')
        print(nn.layer1)
        print('Input')
        print(nn.input)
        print('Weights 1')
        print(nn.weights1)
        print('Weights 2')
        print(nn.weights2)
        print('D Weights 1')
        print(nn.d_weights1)
        print('D Weights 2')
        print(nn.d_weights2)
        print('Output')
        print(nn.output)

------ Iteration 297 ---------
Layer 1
[[0.16331237 0.62437801 0.15886224 0.11622438]
 [0.72672657 0.22126638 0.97096829 0.53515457]
 [0.22185076 0.98848031 0.97728303 0.2429676 ]
 [0.79526356 0.93617378 0.99986875 0.73750741]]
Input
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
Weights 1
[[ 0.38193431  3.95339532  5.43492862  0.89894665]
 [ 2.61828821 -1.77547468  5.182828    2.17601528]
 [-1.64275356  0.51393607 -1.67172116 -2.04170569]]
Weights 2
[[-3.35520567]
 [-3.81707   ]
 [ 7.20222028]
 [-3.43560795]]
D Weights 1
[[-0.01075034]
 [-0.01018126]
 [ 0.01798076]
 [-0.0120619 ]]
D Weights 2
[[ 0.00306165  0.0094566   0.00654639  0.00674407]
 [ 0.00642472 -0.00900029  0.00620486  0.00648404]
 [-0.00896749  0.00576339 -0.00500311 -0.01302515]]
Output
[[0.10158614]
 [0.86653941]
 [0.84346253]
 [0.17289791]]
------ Iteration 298 ---------
Layer 1
[[0.16209073 0.62572873 0.15819484 0.11489316]
 [0.7262213  0.22070914 0.97100215 0.53352701]
 [0.22083289 0.98865234 0.97731727 0.24181416]
 [0.7953480